### ISSUE TITLE
osgeo broken. Can't import gdal successfully

### ISSUE THREAD

**Issue by aidanheerdegen** [ScottWales/conda-envs#5]
```
Package: gdal-2.2.1-np111py27_0
test_environment.py:133: UserWarning: Failed to import osgeo : Reported error: libicui18n.so.58: cannot open shared object file: No such file or directory
  warnings.warn(UserWarning(warnstring))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test_environment.py", line 122, in check_packages
    if importmodule(modname):
  File "test_environment.py", line 130, in importmodule
    import_module(modname, package=None)
  File "/short/v45/aph502/conda/envs/test2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/short/v45/aph502/conda/envs/test2/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/short/v45/aph502/conda/envs/test2/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```

**Comment by aidanheerdegen** [comment]
Looks similar to this:

https://github.com/ContinuumIO/anaconda-issues/issues/1166

**Comment by aidanheerdegen** [comment]
This suggests we need to specify a version of `icu`

https://github.com/conda-forge/libxslt-feedstock/issues/8

**Comment by aidanheerdegen** [comment]
Fixed

https://github.com/ScottWales/conda-envs/commit/fd879189210844142ce67d1a1d38ca37463433c4
